export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAILURE = "SIGNUP_SUCCESS"
export const GETALL_TASKS_SUCCESS = "GETALL_TASKS_SUCCESS"
export const GETALL_TASKS_FAILURE = "GETALL_TASKS_FAILURE"

